FROM node:18-alpine
RUN apk add --no-cache vips-dev build-base python3
WORKDIR /app
COPY package*.json ./
RUN npm install
EXPOSE 4001
CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "npx ts-node src/index.ts"]
